// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: travelpal.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Trip message defines the core "trip" object that will be used throughout the
// API.
type Trip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Destinations  []string               `protobuf:"bytes,5,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trip) Reset() {
	*x = Trip{}
	mi := &file_travelpal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trip) ProtoMessage() {}

func (x *Trip) ProtoReflect() protoreflect.Message {
	mi := &file_travelpal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trip.ProtoReflect.Descriptor instead.
func (*Trip) Descriptor() ([]byte, []int) {
	return file_travelpal_proto_rawDescGZIP(), []int{0}
}

func (x *Trip) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trip) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Trip) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Trip) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Trip) GetDestinations() []string {
	if x != nil {
		return x.Destinations
	}
	return nil
}

// CreateTripRequest defines the request object for creating a new trip.
type CreateTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Trip          *Trip                  `protobuf:"bytes,2,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_travelpal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_travelpal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_travelpal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTripRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTripRequest) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

// CreateTripResponse defines the response object for creating a new trip.
type CreateTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trip          *Trip                  `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripResponse) Reset() {
	*x = CreateTripResponse{}
	mi := &file_travelpal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripResponse) ProtoMessage() {}

func (x *CreateTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_travelpal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripResponse.ProtoReflect.Descriptor instead.
func (*CreateTripResponse) Descriptor() ([]byte, []int) {
	return file_travelpal_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTripResponse) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

// GetTripsRequest defines the request object for retrieving all trips for a
// given user.
type GetTripsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripsRequest) Reset() {
	*x = GetTripsRequest{}
	mi := &file_travelpal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripsRequest) ProtoMessage() {}

func (x *GetTripsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_travelpal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripsRequest.ProtoReflect.Descriptor instead.
func (*GetTripsRequest) Descriptor() ([]byte, []int) {
	return file_travelpal_proto_rawDescGZIP(), []int{3}
}

func (x *GetTripsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetTripsResponse defines the response object for retrieving all trips for a
// given user.
type GetTripsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trips         []*Trip                `protobuf:"bytes,1,rep,name=trips,proto3" json:"trips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripsResponse) Reset() {
	*x = GetTripsResponse{}
	mi := &file_travelpal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripsResponse) ProtoMessage() {}

func (x *GetTripsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_travelpal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripsResponse.ProtoReflect.Descriptor instead.
func (*GetTripsResponse) Descriptor() ([]byte, []int) {
	return file_travelpal_proto_rawDescGZIP(), []int{4}
}

func (x *GetTripsResponse) GetTrips() []*Trip {
	if x != nil {
		return x.Trips
	}
	return nil
}

var File_travelpal_proto protoreflect.FileDescriptor

const file_travelpal_proto_rawDesc = "" +
	"\n" +
	"\x0ftravelpal.proto\x12\ftravelpal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\x04Trip\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\"\n" +
	"\fdestinations\x18\x05 \x03(\tR\fdestinations\"T\n" +
	"\x11CreateTripRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x04trip\x18\x02 \x01(\v2\x12.travelpal.v1.TripR\x04trip\"<\n" +
	"\x12CreateTripResponse\x12&\n" +
	"\x04trip\x18\x01 \x01(\v2\x12.travelpal.v1.TripR\x04trip\"*\n" +
	"\x0fGetTripsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"<\n" +
	"\x10GetTripsResponse\x12(\n" +
	"\x05trips\x18\x01 \x03(\v2\x12.travelpal.v1.TripR\x05trips2\xb2\x01\n" +
	"\x10TravelPalService\x12Q\n" +
	"\n" +
	"CreateTrip\x12\x1f.travelpal.v1.CreateTripRequest\x1a .travelpal.v1.CreateTripResponse\"\x00\x12K\n" +
	"\bGetTrips\x12\x1d.travelpal.v1.GetTripsRequest\x1a\x1e.travelpal.v1.GetTripsResponse\"\x00B)Z'TravelPalBackEnd/pkg/proto/travelpal/v1b\x06proto3"

var (
	file_travelpal_proto_rawDescOnce sync.Once
	file_travelpal_proto_rawDescData []byte
)

func file_travelpal_proto_rawDescGZIP() []byte {
	file_travelpal_proto_rawDescOnce.Do(func() {
		file_travelpal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_travelpal_proto_rawDesc), len(file_travelpal_proto_rawDesc)))
	})
	return file_travelpal_proto_rawDescData
}

var file_travelpal_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_travelpal_proto_goTypes = []any{
	(*Trip)(nil),                  // 0: travelpal.v1.Trip
	(*CreateTripRequest)(nil),     // 1: travelpal.v1.CreateTripRequest
	(*CreateTripResponse)(nil),    // 2: travelpal.v1.CreateTripResponse
	(*GetTripsRequest)(nil),       // 3: travelpal.v1.GetTripsRequest
	(*GetTripsResponse)(nil),      // 4: travelpal.v1.GetTripsResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_travelpal_proto_depIdxs = []int32{
	5, // 0: travelpal.v1.Trip.start_date:type_name -> google.protobuf.Timestamp
	5, // 1: travelpal.v1.Trip.end_date:type_name -> google.protobuf.Timestamp
	0, // 2: travelpal.v1.CreateTripRequest.trip:type_name -> travelpal.v1.Trip
	0, // 3: travelpal.v1.CreateTripResponse.trip:type_name -> travelpal.v1.Trip
	0, // 4: travelpal.v1.GetTripsResponse.trips:type_name -> travelpal.v1.Trip
	1, // 5: travelpal.v1.TravelPalService.CreateTrip:input_type -> travelpal.v1.CreateTripRequest
	3, // 6: travelpal.v1.TravelPalService.GetTrips:input_type -> travelpal.v1.GetTripsRequest
	2, // 7: travelpal.v1.TravelPalService.CreateTrip:output_type -> travelpal.v1.CreateTripResponse
	4, // 8: travelpal.v1.TravelPalService.GetTrips:output_type -> travelpal.v1.GetTripsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_travelpal_proto_init() }
func file_travelpal_proto_init() {
	if File_travelpal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_travelpal_proto_rawDesc), len(file_travelpal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_travelpal_proto_goTypes,
		DependencyIndexes: file_travelpal_proto_depIdxs,
		MessageInfos:      file_travelpal_proto_msgTypes,
	}.Build()
	File_travelpal_proto = out.File
	file_travelpal_proto_goTypes = nil
	file_travelpal_proto_depIdxs = nil
}
