// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: travelpal.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TravelPalService_CreateTrip_FullMethodName = "/travelpal.v1.TravelPalService/CreateTrip"
	TravelPalService_GetTrips_FullMethodName   = "/travelpal.v1.TravelPalService/GetTrips"
)

// TravelPalServiceClient is the client API for TravelPalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TravelPalServiceClient interface {
	// CreateTrip defines a new trip for a given user.
	CreateTrip(ctx context.Context, in *CreateTripRequest, opts ...grpc.CallOption) (*CreateTripResponse, error)
	// GetTrips retrieves all Trips for a relevant user.
	GetTrips(ctx context.Context, in *GetTripsRequest, opts ...grpc.CallOption) (*GetTripsResponse, error)
}

type travelPalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTravelPalServiceClient(cc grpc.ClientConnInterface) TravelPalServiceClient {
	return &travelPalServiceClient{cc}
}

func (c *travelPalServiceClient) CreateTrip(ctx context.Context, in *CreateTripRequest, opts ...grpc.CallOption) (*CreateTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTripResponse)
	err := c.cc.Invoke(ctx, TravelPalService_CreateTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *travelPalServiceClient) GetTrips(ctx context.Context, in *GetTripsRequest, opts ...grpc.CallOption) (*GetTripsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTripsResponse)
	err := c.cc.Invoke(ctx, TravelPalService_GetTrips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TravelPalServiceServer is the server API for TravelPalService service.
// All implementations must embed UnimplementedTravelPalServiceServer
// for forward compatibility.
type TravelPalServiceServer interface {
	// CreateTrip defines a new trip for a given user.
	CreateTrip(context.Context, *CreateTripRequest) (*CreateTripResponse, error)
	// GetTrips retrieves all Trips for a relevant user.
	GetTrips(context.Context, *GetTripsRequest) (*GetTripsResponse, error)
	mustEmbedUnimplementedTravelPalServiceServer()
}

// UnimplementedTravelPalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTravelPalServiceServer struct{}

func (UnimplementedTravelPalServiceServer) CreateTrip(context.Context, *CreateTripRequest) (*CreateTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrip not implemented")
}
func (UnimplementedTravelPalServiceServer) GetTrips(context.Context, *GetTripsRequest) (*GetTripsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrips not implemented")
}
func (UnimplementedTravelPalServiceServer) mustEmbedUnimplementedTravelPalServiceServer() {}
func (UnimplementedTravelPalServiceServer) testEmbeddedByValue()                          {}

// UnsafeTravelPalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TravelPalServiceServer will
// result in compilation errors.
type UnsafeTravelPalServiceServer interface {
	mustEmbedUnimplementedTravelPalServiceServer()
}

func RegisterTravelPalServiceServer(s grpc.ServiceRegistrar, srv TravelPalServiceServer) {
	// If the following call pancis, it indicates UnimplementedTravelPalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TravelPalService_ServiceDesc, srv)
}

func _TravelPalService_CreateTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TravelPalServiceServer).CreateTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TravelPalService_CreateTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TravelPalServiceServer).CreateTrip(ctx, req.(*CreateTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TravelPalService_GetTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TravelPalServiceServer).GetTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TravelPalService_GetTrips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TravelPalServiceServer).GetTrips(ctx, req.(*GetTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TravelPalService_ServiceDesc is the grpc.ServiceDesc for TravelPalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TravelPalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "travelpal.v1.TravelPalService",
	HandlerType: (*TravelPalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrip",
			Handler:    _TravelPalService_CreateTrip_Handler,
		},
		{
			MethodName: "GetTrips",
			Handler:    _TravelPalService_GetTrips_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "travelpal.proto",
}
